# Generated by Django 4.0.2 on 2022-02-18 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('date', models.DateField(verbose_name='Application Submitted')),
                ('desciption', models.TextField(max_length=250)),
            ],
        ),
    ]
