# Generated by Django 4.0.2 on 2022-02-19 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='desciption',
            new_name='description',
        ),
    ]
