# Generated by Django 4.0.2 on 2022-02-23 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_jobs_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='date',
            field=models.DateField(verbose_name='Date (YYYY/MM/DD)'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='description',
            field=models.TextField(verbose_name='Notes'),
        ),
        migrations.CreateModel(
            name='Resp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Response Date')),
                ('resp_name', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('notes', models.TextField(max_length=350)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.jobs')),
            ],
        ),
        migrations.CreateModel(
            name='Reout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Reachout Date')),
                ('reout_name', models.CharField(max_length=100, verbose_name='Contact Name')),
                ('source', models.CharField(max_length=100)),
                ('notes', models.TextField(max_length=350)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.jobs')),
            ],
        ),
    ]
